### ISSUE TITLE
implement freeserver command + Implement Matchendscreen and kick Players

### ISSUE THREAD

**Issue by Apfelwurm** [Lan2Play/PugSharp#11]
we have to add the freeserver api call, so the server can tell the api when its free to receive the next match.

This should respect if hltv is done with broadcasting (because of the delay) -> https://github.com/Lan2Play/PugSharp/issues/10 .

Also depending on the nessecary time we should add an Match end screen and kick all the players, so the server is really free.

**Comment by TheR00st3r** [comment]
@Apfelwurm das sollte doch auch erledigt sein?

**Comment by Apfelwurm** [comment]
@TheR00st3r bin nicht sicher ob ihr das schon so eingebaut und getestet habt, kann aber gut sein

**Comment by TheR00st3r** [comment]
This is done
