### ISSUE TITLE
Match Config File won't load

### ISSUE THREAD

**Issue by lanslide-team** [Lan2Play/PugSharp#125]
Metamod:Source version 2.0.0-dev+1275
CSS: Current API Version: 129
PugSharp Alpha Build: https://github.com/Lan2Play/PugSharp/actions/runs/7266830432/artifacts/1124961232 [latest_build_linux_with_cssharp_and_runtime]

[match.json](https://github.com/Lan2Play/PugSharp/files/13740646/match.json)

When I try to load the match config, I get this error:
`CSSharp: Native 5d4ee1c2 was invoked on a non-main thread`

**Comment by DrkwnM** [comment]
Try loading it with this setup instead:

`{
    "maplist": [
        "de_ancient",
        "de_anubis",
        "de_inferno",
        "de_mirage",
        "de_nuke",
        "de_overpass",
        "de_vertigo"
    ],
    "team1": {
        "id": "1",
        "name": "A Team",
        "tag": null,
        "flag": "AU",
        "players":{"123321":"Username"}
    },
    "team2": {
        "id": "2",
        "name": "B Team",
        "tag": null,
        "flag": "AU",
        "players":{"123321":"Username"}
    },
    "matchid": "1",
    "num_maps": 1,
    "players_per_team": 5,
    "min_players_to_ready": 5,
    "max_rounds": 24,
    "max_overtime_rounds": 6,
    "vote_timeout": 60000,
    "eventula_apistats_url": null,
    "eventula_apistats_token": null,
    "eventula_demo_upload_url": null,
    "allow_suicide": true,
    "vote_map": null,
    "team_mode": 0,
    "cvars": {
        "get5_remote_log_url": "https://g5.lanslide.com.au/api",
        "get5_remote_log_header_key": "Authorization",
        "get5_remote_log_header_value": "6583bac9a2455",
        "wingman": "false",
        "side_type": "standard",
        "veto_first": "team1",
        "skip_veto": "false"
    }
}`

The above worked for me with ps_loadconfig <url>.

**Comment by lanslide-team** [comment]
Apart from adding a player, I see you made match ID a string. I have applied these changes.
```
ps_loadconfig "https://portal.lanslide.com.au/match.json"
ps_loadconfigfile match.json
```

Remote config file works, however one of two things happens:
- The plugin locks you in spectator mode and you can't enter chat messages
- You can enter "!ready", but it doesn't change your ready state
 but the ready system doesn't load properly (players can not ready up).
Local config file - fails with the original error.

**Comment by brendontaylor** [comment]
Downloaded the latest repository and tested in Linux.
Good news is the config now seems to be loading correctly.

**Comment by lanslide-team** [comment]
Downloaded the latest repository and tested in Linux.
Good news is the config now seems to be loading correctly.
