### ISSUE TITLE
path of plugin under linux maybe wrong

### ISSUE THREAD

**Issue by Toutzn** [Lan2Play/PugSharp#24]
if I try to use the plugin, the cogs server says:

L 11/14/2023 - 10:55:21: [META] Failed to load plugin addons/counterstrikesharp/bin/win64/counterstrikesharp: File not found: /home/lgsm/serverfiles/game/csgo/addons/counterstrikesharp/bin/win64/counterstrikesharp.so
L 11/14/2023 - 10:55:21: [META] Loaded 0 plugins.

In the linux zip package, there is no file called counterstrikesharp.so
The original from roflmuffin/CounterStrikeSharp there is the file.

could it be that the linux package was packed incorrectly?

BR. Torsten

**Comment by Apfelwurm** [comment]
Thanks for reporting, going to look into it later today :)
