### ISSUE TITLE
Start Match via G5

### ISSUE THREAD

**Issue by Toutzn** [Lan2Play/PugSharp#45]
If you start a match it goes into an error like:

info: PugSharp.Match.Match[0] MatchState Changed: None => WaitingForPlayersConnectedReady
**fail: PugSharp.PugSharp[0] Config /home/lgsm/serverfiles/game/csgo/cfg/PugSharp/warmup.cfg was not found on the server.**
info: PugSharp.Match.Match[0] Reset Readystate for all players

**Comment by Apfelwurm** [comment]
somehow the copying of the configs is messed up. going to fix that. Thanks for reporting!

**Comment by Apfelwurm** [comment]
fixed in https://github.com/Lan2Play/PugSharp/releases/tag/v0.1.4-beta
