### ISSUE TITLE
Make kicking of players when no match is loaded optional and configurable

### ISSUE THREAD

**Issue by deLuXe83** [Lan2Play/PugSharp#73]
Hi,
currently Pugsharp is always activated.
Therefore you cannot play training matches or deathmatch because bots always gets immediately kicked:

`ClientPutInServer create new player controller [Hugg]
"Hugg<0><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 2 willSwitch 0, 1.53 
info: PugSharp.PugSharp[0] OnPlayerTeam called. Hugg tries to join 2 IsHLTV: False IsBot True
info: PugSharp.PugSharp[0] No match is loaded. Kick Player Hugg!
info: PugSharp.PugSharp[0] OnRoundEnd called
ClientPutInServer create new player controller [Trapper]
"Trapper<1><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 3 willSwitch 0, 1.53 
info: PugSharp.PugSharp[0] OnPlayerTeam called. Trapper tries to join 3 IsHLTV: False IsBot True
info: PugSharp.PugSharp[0] No match is loaded. Kick Player Trapper!
Host activate: Loading (de_dust2)
Hugg kicked by Console ("You are not part of the current match!")
info: PugSharp.PugSharp[0] Player Hugg has disconnected!
Trapper kicked by Console ("You are not part of the current match!")
info: PugSharp.PugSharp[0] Player Trapper has disconnected!`

EDIT:
Not only bots get kicked.
Also human players are not able to join the server, if no match config is loaded!

EDIt2:
gets even weirder :)
After ending a testmatch with "!ps_stopmatch", the match stops and the map changes, but the console got flooded with kicking bot messages:
![grafik](https://github.com/Lan2Play/PugSharp/assets/37928770/44f655c2-74eb-49b1-b6c0-22562cf00bf7)

**Comment by Apfelwurm** [comment]
As of now this behaviour is intended, because we had strange problems with players being fully contected before the match loads (due to inconsistent event firing behaviour of CS2). We are aware that this is not optimal, and we want to make this behaviour optional and configurable in the future, because we also want to implement configuration of the Matches on the server itself. Thanks for opening this issue :)

**Comment by TheR00st3r** [comment]
fixed by #94
